"""tracker app db init

Revision ID: c5b895d7cf74
Revises: 
Create Date: 2023-07-14 16:41:24.285898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5b895d7cf74'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('street_name', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('pincode', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('carrier',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_carrier_id'), 'carrier', ['id'], unique=False)
    op.create_table('shipmentstatus',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('articlesku',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('price', sa.DECIMAL(), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tracking_id', sa.String(), nullable=False),
    sa.Column('carrier_id', sa.UUID(), nullable=False),
    sa.Column('source_address_id', sa.Integer(), nullable=False),
    sa.Column('destination_address_id', sa.Integer(), nullable=False),
    sa.Column('shipment_status_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['carrier_id'], ['carrier.id'], ),
    sa.ForeignKeyConstraint(['destination_address_id'], ['address.id'], ),
    sa.ForeignKeyConstraint(['shipment_status_id'], ['shipmentstatus.id'], ),
    sa.ForeignKeyConstraint(['source_address_id'], ['address.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipment_carrier_id'), 'shipment', ['carrier_id'], unique=False)
    op.create_index(op.f('ix_shipment_tracking_id'), 'shipment', ['tracking_id'], unique=True)
    op.create_table('shipmentitem',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('article_sku_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_sku_id'], ['articlesku.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipmentitem_shipment_id'), 'shipmentitem', ['shipment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shipmentitem_shipment_id'), table_name='shipmentitem')
    op.drop_table('shipmentitem')
    op.drop_index(op.f('ix_shipment_tracking_id'), table_name='shipment')
    op.drop_index(op.f('ix_shipment_carrier_id'), table_name='shipment')
    op.drop_table('shipment')
    op.drop_table('articlesku')
    op.drop_table('shipmentstatus')
    op.drop_index(op.f('ix_carrier_id'), table_name='carrier')
    op.drop_table('carrier')
    op.drop_table('article')
    op.drop_table('address')
    # ### end Alembic commands ###
